### PR TITLE
[feature request]: implement shorthand for `@readonly` as `z.literal()`

### PR DESCRIPTION
**Pull request by sakgoyal**

### CODE REVIEW

**Comment by ymc9** [comment]
Hi @sakgoyal , thanks for the PR again 😄.

I want to be conservative with introducing new attributes because each of them adds some cognitive cost to the users. May I keep this PR on hold until we get a few more similar ask for the feature? If your main need here is zod schema here, maybe you can also use zod API to extend the generated schemas?

**Comment by sakgoyal** [comment]
that is why I kept it as a draft. I wanted feedback before continuing. 
I will gladly wait since it is not urgent for me.

**Comment by ymc9** [comment]
> that is why I kept it as a draft. I wanted feedback before continuing. I will gladly wait since it is not urgent for me.

Got it. Thanks for understanding!

**Comment by ymc9** [comment]
Closing for now since there's no plan to merge in the near future

**Pull request closed without merging**
