### PR TITLE
fix: require with default

### PR DESCRIPTION
**Pull request by chemitaxis**
This PR solves https://github.com/zenstackhq/zenstack/issues/545 

@ymc9 :) 

Please if everything os would be awesome if you make a new release, thanks!!

### CODE REVIEW

**Comment by chemitaxis** [comment]
Thanks @ymc9 I'm trying to remove the `package.lock` but I'm not so good with forks :(

**Comment by ymc9** [comment]
> This PR solves #545
> 
> @ymc9 :)
> 
> Please if everything os would be awesome if you make a new release, thanks!!

Good catch! Do you mind reverting the change of pnpm-lock file? Thanks! @chemitaxis 

Btw, if you create your local branch based on the "dev" branch, the PR history will look cleaner I guess.

**Comment by ymc9** [comment]
Btw what version of pnpm are you using? I suspect upgrading to the latest version will resolve the problem that the lock file is always updated ...

**Comment by ymc9** [comment]
> Thanks @ymc9 I'm trying to remove the `package.lock` but I'm not so good with forks :(

No worries, let me see how to add you to the contributor group after this PR is merged 😄

**Comment by chemitaxis** [comment]
hi @ymc9 done!! 👏

**Comment by ymc9** [comment]
> hi @ymc9 done!! 👏

Cool! Will merge when CI completes.

**Pull request merged**
