### PR TITLE
feat: create prefetch functions for Tanstack Query plugin

### PR DESCRIPTION
**Pull request by Arkanii**
Hello!

I need help with this one. 😓
I'm trying to run this on Svelte but [prefetch queries need to be executed on the server](https://tanstack.com/query/latest/docs/framework/svelte/ssr) so I can't use the `getHooksContext` function and I can't find any solution for it yet.

I also need to test on Vue and React. If anyone can test it that would be great as I don't have much time to test on all three frameworks. 🙏🏻 

Thanks !

```
Svelte error: lifecycle_outside_component
2024-09-18T16:10:51.139896568Z `getContext(...)` can only be used during component initialisation
2024-09-18T16:10:51.139903231Z     at Module.lifecycle_outside_component (/srv/app/node_modules/svelte/src/internal/shared/errors.js:28:17)
2024-09-18T16:10:51.139909643Z     at get_or_init_context_map (/srv/app/node_modules/svelte/src/internal/server/context.js:51:5)
2024-09-18T16:10:51.139915794Z     at Module.getContext (/srv/app/node_modules/svelte/src/internal/server/context.js:15:22)
2024-09-18T16:10:51.139921936Z     at Module.getHooksContext (/srv/app/node_modules/@zenstackhq/src/runtime-v5/svelte.ts:48:35)
2024-09-18T16:10:51.139963213Z     at Module.usePrefetchFindManyTodo (/srv/app/src/lib/hooks/todo.ts:65:33)
2024-09-18T16:10:51.139967551Z     at load (/srv/app/src/routes/(website)/(home)/+page.ts:7:8)
2024-09-18T16:10:51.139971478Z     at async Module.load_data (/srv/app/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:192:17)
2024-09-18T16:10:51.139975546Z     at async eval (/srv/app/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:168:13)
```

### CODE REVIEW

**Comment by ymc9** [comment]
Hey @Arkanii , thanks for making this PR. I'll follow up here a bit later.

**Comment by ymc9** [comment]
> Hello!
> 
> I need help with this one. 😓 I'm trying to run this on Svelte but [prefetch queries need to be executed on the server](https://tanstack.com/query/latest/docs/framework/svelte/ssr) so I can't use the `getHooksContext` function and I can't find any solution for it yet.
> 
> I also need to test on Vue and React. If anyone can test it that would be great as I don't have much time to test on all three frameworks. 🙏🏻
> 
> Thanks !
> 
> ```
> Svelte error: lifecycle_outside_component
> 2024-09-18T16:10:51.139896568Z `getContext(...)` can only be used during component initialisation
> 2024-09-18T16:10:51.139903231Z     at Module.lifecycle_outside_component (/srv/app/node_modules/svelte/src/internal/shared/errors.js:28:17)
> 2024-09-18T16:10:51.139909643Z     at get_or_init_context_map (/srv/app/node_modules/svelte/src/internal/server/context.js:51:5)
> 2024-09-18T16:10:51.139915794Z     at Module.getContext (/srv/app/node_modules/svelte/src/internal/server/context.js:15:22)
> 2024-09-18T16:10:51.139921936Z     at Module.getHooksContext (/srv/app/node_modules/@zenstackhq/src/runtime-v5/svelte.ts:48:35)
> 2024-09-18T16:10:51.139963213Z     at Module.usePrefetchFindManyTodo (/srv/app/src/lib/hooks/todo.ts:65:33)
> 2024-09-18T16:10:51.139967551Z     at load (/srv/app/src/routes/(website)/(home)/+page.ts:7:8)
> 2024-09-18T16:10:51.139971478Z     at async Module.load_data (/srv/app/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:192:17)
> 2024-09-18T16:10:51.139975546Z     at async eval (/srv/app/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:168:13)
> ```

Hi @Arkanii , my apologies for the late response. Just to clarify your goal here. Do you want to do server-side prefetch with SvelteKit? If so, maybe we should simply generate a set of `presetFindManyModel` etc. async functions (that wraps `queryClient.prefetchQuery` inside), instead of generating `usePrefetchQuery`?

**Comment by Arkanii** [comment]
> > Hello!
> > I need help with this one. 😓 I'm trying to run this on Svelte but [prefetch queries need to be executed on the server](https://tanstack.com/query/latest/docs/framework/svelte/ssr) so I can't use the `getHooksContext` function and I can't find any solution for it yet.
> > I also need to test on Vue and React. If anyone can test it that would be great as I don't have much time to test on all three frameworks. 🙏🏻
> > Thanks !
> > ```
> > Svelte error: lifecycle_outside_component
> > 2024-09-18T16:10:51.139896568Z `getContext(...)` can only be used during component initialisation
> > 2024-09-18T16:10:51.139903231Z     at Module.lifecycle_outside_component (/srv/app/node_modules/svelte/src/internal/shared/errors.js:28:17)
> > 2024-09-18T16:10:51.139909643Z     at get_or_init_context_map (/srv/app/node_modules/svelte/src/internal/server/context.js:51:5)
> > 2024-09-18T16:10:51.139915794Z     at Module.getContext (/srv/app/node_modules/svelte/src/internal/server/context.js:15:22)
> > 2024-09-18T16:10:51.139921936Z     at Module.getHooksContext (/srv/app/node_modules/@zenstackhq/src/runtime-v5/svelte.ts:48:35)
> > 2024-09-18T16:10:51.139963213Z     at Module.usePrefetchFindManyTodo (/srv/app/src/lib/hooks/todo.ts:65:33)
> > 2024-09-18T16:10:51.139967551Z     at load (/srv/app/src/routes/(website)/(home)/+page.ts:7:8)
> > 2024-09-18T16:10:51.139971478Z     at async Module.load_data (/srv/app/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:192:17)
> > 2024-09-18T16:10:51.139975546Z     at async eval (/srv/app/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:168:13)
> > ```
> 
> Hi @Arkanii , my apologies for the late response. Just to clarify your goal here. Do you want to do server-side prefetch with SvelteKit? If so, maybe we should simply generate a set of `presetFindManyModel` etc. async functions (that wraps `queryClient.prefetchQuery` inside), instead of generating `usePrefetchQuery`?

Hello ! No problem. 😄 
Yes, my goal here is to do server-side prefetch with SvelteKit to reduce loading times, and to do it for other frameworks too if it can helps someone.

**Comment by Arkanii** [comment]
Mmmh I think it's too complicated for me to end this...
Do you have any tip for me ? thanks

**Comment by ymc9** [comment]
> Mmmh I think it's too complicated for me to end this... Do you have any tip for me ? thanks

No worries @Arkanii , I'll follow up on this PR!

**Comment by ymc9** [comment]
Hi @Arkanii , I've made some progress to change the PR to generate `prefetch[Action][Model]` and `fetch[Action][Model]` instead, which is probably more versatile than `usePrefetch`.

However, I believe more though and work is needed about how data is actually fetched from the server side. It's complicated and not performant if the hooks still send an HTTP request. It should probably just directly call enhanced prisma client.

May I keep the PR open for now and continue thinking about this? I really appreciate that you started this effort. It's been a long-waited feature!

**Comment by Arkanii** [comment]
> Hi @Arkanii , I've made some progress to change the PR to generate `prefetch[Action][Model]` and `fetch[Action][Model]` instead, which is probably more versatile than `usePrefetch`.
> 
> However, I believe more though and work is needed about how data is actually fetched from the server side. It's complicated and not performant if the hooks still send an HTTP request. It should probably just directly call enhanced prisma client.
> 
> May I keep the PR open for now and continue thinking about this? I really appreciate that you started this effort. It's been a long-waited feature!

Sure no problem ! I'll just put it in draft.
Thanks to you to accept to work my PR. 🙏🏻

**Comment by Arkanii** [comment]
ops sorry @ymc9 I closed the PR...

**Pull request closed without merging**
